image: node:12.13.1

pipelines:
  branches:
    master:
      - step:
          caches:
            - node
          deployment: production
          script: 
            - cd online.codingblocks.com
            - yarn install
            - yarn build:prod
            - ls
            - ../deploy.sh

    development:
      - step:
          caches:
            - node
          deployment: staging
          script: 
            - cd online.codingblocks.com
            - yarn install
            - yarn build
            - ls
            - ../deploy.sh
