image: node:12.13.1

pipelines:
  branches:
    master:
      - step:
          caches:
            - node
          deployment: production
          script: 
            - cd online.codingblocks.com
            - yarn install --frozen-lockfile
            - yarn build:prod
            - ls
            - ../deploy-production.sh

    development:
      - step:
          caches:
            - node
          deployment: staging
          script: 
            - cd online.codingblocks.com
            - yarn install --frozen-lockfile
            - yarn build
            - ls
            - ../deploy-staging.sh
